name: Atualizar KS na StackSpot

on:
  push:
    paths:
      - 'README.md' 
    branches:
      - main

jobs:
  update-ks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar o STK CLI
        run: |
          curl -fsSL https://cli.stackspot.com/install.sh | bash
          export PATH="$HOME/.stk/bin:$PATH"

      - name: Autenticar no StackSpot
        run: |
          $HOME/.stk/bin/stk login --client-id ${{ secrets.CLIENT_ID }} --client-key ${{ secrets.CLIENT_KEY }} --realm ${{ secrets.CLIENT_REALM }}

      - name: Atualizar o KS
        run: |
            $HOME/.stk/bin/stk ks update --path ./README.md 
