name: Atualizar KS na StackSpot

on:
  push:
    paths:
      - 'https://github.com/eloiza-souza/productsCRUD/blob/main/README.md' # ajuste para o caminho do seu KS
    branches:
      - main # ou a branch que desejar monitorar

jobs:
  update-ks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar o STK CLI
        run: |
          curl -fsSL https://cli.stackspot.com/install.sh | bash
          export PATH="$HOME/.stk/bin:$PATH"

      - name: Autenticar no StackSpot
        run: |
          $HOME/.stk/bin/stk login --client-id ${{ secrets.CLIENT_ID }} --client-key ${{ secrets.CLIENT_KEY }} --realm ${{ secrets.CLIENT_REALM }}

      - name: Atualizar o KS
        run: |
          stk ks update --path https://ai.stackspot.com/knowledge-sources/e19cf5-updatetest?tabIndex=0
